In [1]:
# Basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Normalization  libraries
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error, r2_score

# Easy graphs with plotly
import plotly.express as px
import plotly.graph_objects as go

# Matplotlib plots look like
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (15,7)
import pickle as pk

import scipy
from scipy import stats

In [2]:
original = pd.read_csv('./outputs/Training_comparativos/corrida_original.csv')
'''
uno = pd.read_csv('./outputs/Training_comparativos/corrida_uno.csv')
uno.rename(columns={'MAPE': 'MAPE_uno', 'R2':'R2_uno'}, inplace=True)
dos = pd.read_csv('./outputs/Training_comparativos/corrida_dos.csv')
dos.rename(columns={'MAPE': 'MAPE_dos', 'R2':'R2_dos'}, inplace=True)
tres = pd.read_csv('./outputs/Training_comparativos/corrida_tres.csv')
tres.rename(columns={'MAPE': 'MAPE_tres', 'R2':'R2_tres'}, inplace=True)
cuatro = pd.read_csv('./outputs/Training_comparativos/corrida_cuatro.csv')
cuatro.rename(columns={'MAPE': 'MAPE_cuatro', 'R2':'R2_cuatro'}, inplace=True)
'''
original

     Unnamed: 0           FECHA-HORA      MAPE        R2
0             0  2021-05-08 23:00:00  1.231354  0.991257
1             1  2021-05-09 23:00:00  1.473915  0.987307
2             2  2021-05-10 23:00:00  2.501177  0.994960
3             3  2021-05-11 23:00:00  3.117464  0.967477
4             4  2021-05-12 23:00:00  2.743412  0.985523
..          ...                  ...       ...       ...
352         352  2022-04-25 23:00:00  1.904066  0.989241
353         353  2022-04-26 23:00:00  2.102692  0.992158
354         354  2022-04-27 23:00:00  1.828459  0.994503
355         355  2022-04-28 23:00:00  3.341231  0.995226
356         356  2022-04-29 23:00:00  1.373173  0.991852

[357 rows x 4 columns]

In [3]:
uno = pd.read_csv('./outputs/Training_comparativos/corrida_may_jun.csv')
uno

    Unnamed: 0           FECHA-HORA      MAPE        R2
0            0  2021-05-08 23:00:00  1.010311  0.994103
1            1  2021-05-09 23:00:00  1.038688  0.996063
2            2  2021-05-10 23:00:00  1.828785  0.980243
3            3  2021-05-11 23:00:00  4.269057  0.965788
4            4  2021-05-12 23:00:00  5.593381  0.985341
5            5  2021-05-13 23:00:00  3.028426  0.992476
6            6  2021-05-14 23:00:00  2.796986  0.997488
7            7  2021-05-15 23:00:00  1.504883  0.991874
8            8  2021-05-16 23:00:00  1.462997  0.987389
9            9  2021-05-17 23:00:00  4.471234  0.995001
10          10  2021-05-18 23:00:00  0.977468  0.997852
11          11  2021-05-19 23:00:00  1.116162  0.996777
12          12  2021-05-20 23:00:00  1.229904  0.994151
13          13  2021-05-21 23:00:00  2.946266  0.963250
14          14  2021-05-22 23:00:00  0.855743  0.997326
15          15  2021-05-23 23:00:00  0.957627  0.997532
16          16  2021-05-24 23:00:00  1.482501  0.996430
17          17  2021-05-25 23:00:00  1.212807  0.997839
18          18  2021-05-26 23:00:00  0.978130  0.998603
19          19  2021-05-27 23:00:00  0.972563  0.999084
20          20  2021-05-28 23:00:00  2.650162  0.996674
21          21  2021-05-29 23:00:00  2.239571  0.998822
22          22  2021-05-30 23:00:00  1.624100  0.993872
23          23  2021-05-31 23:00:00  3.909295  0.991090
24          24  2021-06-01 23:00:00  0.879925  0.999191
25          25  2021-06-02 23:00:00  2.690697  0.998344
26          26  2021-06-03 23:00:00  0.916398  0.998349
27          27  2021-06-04 23:00:00  1.481891  0.994799
28          28  2021-06-05 23:00:00  3.188200  0.997335
29          29  2021-06-06 23:00:00  1.915578  0.988082
30          30  2021-06-07 23:00:00  0.857860  0.995634
31          31  2021-06-08 23:00:00  1.785306  0.998274
32          32  2021-06-09 23:00:00  2.031002  0.998218
33          33  2021-06-10 23:00:00  2.088436  0.997156
34          34  2021-06-11 23:00:00  2.829011  0.996646
35          35  2021-06-12 23:00:00  1.370681  0.988545
36          36  2021-06-13 23:00:00  2.330206  0.992955
37          37  2021-06-14 23:00:00  1.050707  0.997968
38          38  2021-06-15 23:00:00  2.158454  0.995736
39          39  2021-06-16 23:00:00  5.183827  0.988791
40          40  2021-06-17 23:00:00  4.300207  0.990609
41          41  2021-06-18 23:00:00  2.359590  0.977569
42          42  2021-06-19 23:00:00  3.535810  0.973193
43          43  2021-06-20 23:00:00  3.082903  0.906639
44          44  2021-06-21 23:00:00  1.155819  0.994050
45          45  2021-06-22 23:00:00  0.968833  0.995137
46          46  2021-06-23 23:00:00  2.929515  0.961534
47          47  2021-06-24 23:00:00  3.292342  0.968261
48          48  2021-06-25 23:00:00  2.036670  0.981730
49          49  2021-06-26 23:00:00  3.297941  0.983635
50          50  2021-06-27 23:00:00  5.351269  0.975301
51          51  2021-06-28 23:00:00  1.150325  0.991835
52          52  2021-06-29 23:00:00  5.267760  0.956858

In [4]:
dos = pd.read_csv('./outputs/Training_comparativos/corrida_jul_ago.csv')
tres = pd.read_csv('./outputs/Training_comparativos/corrida_sep_oct.csv')
cuatro = pd.read_csv('./outputs/Training_comparativos/corrida_nov_dic.csv')

In [5]:
retraining = pd.concat([uno, dos])
retraining = pd.concat([retraining, tres])
retraining = pd.concat([retraining, cuatro])
retraining.rename(columns={'MAPE': 'MAPE_rt', 'R2':'R2_rt'}, inplace=True)
retraining

    Unnamed: 0           FECHA-HORA   MAPE_rt     R2_rt
0            0  2021-05-08 23:00:00  1.010311  0.994103
1            1  2021-05-09 23:00:00  1.038688  0.996063
2            2  2021-05-10 23:00:00  1.828785  0.980243
3            3  2021-05-11 23:00:00  4.269057  0.965788
4            4  2021-05-12 23:00:00  5.593381  0.985341
..         ...                  ...       ...       ...
49          49  2021-12-26 23:00:00  4.306156  0.990965
50          50  2021-12-27 23:00:00  5.659207  0.985588
51          51  2021-12-28 23:00:00  4.611348  0.982034
52          52  2021-12-29 23:00:00  3.728256  0.989159
53          53  2021-12-30 23:00:00  2.475101  0.992799

[213 rows x 4 columns]

In [6]:
original = pd.merge(original, retraining[['FECHA-HORA', 'MAPE_rt', 'R2_rt']], on='FECHA-HORA', how='left')
original

     Unnamed: 0           FECHA-HORA      MAPE        R2   MAPE_rt     R2_rt
0             0  2021-05-08 23:00:00  1.231354  0.991257  1.010311  0.994103
1             1  2021-05-09 23:00:00  1.473915  0.987307  1.038688  0.996063
2             2  2021-05-10 23:00:00  2.501177  0.994960  1.828785  0.980243
3             3  2021-05-11 23:00:00  3.117464  0.967477  4.269057  0.965788
4             4  2021-05-12 23:00:00  2.743412  0.985523  5.593381  0.985341
..          ...                  ...       ...       ...       ...       ...
352         352  2022-04-25 23:00:00  1.904066  0.989241       NaN       NaN
353         353  2022-04-26 23:00:00  2.102692  0.992158       NaN       NaN
354         354  2022-04-27 23:00:00  1.828459  0.994503       NaN       NaN
355         355  2022-04-28 23:00:00  3.341231  0.995226       NaN       NaN
356         356  2022-04-29 23:00:00  1.373173  0.991852       NaN       NaN

[357 rows x 6 columns]

## Histogramas MAPES

In [22]:

fig = px.histogram(original, x="MAPE", nbins=13, title="Histograma MAPE Datos Originales")
fig.show()

In [17]:
fig = px.histogram(original, x="MAPE_rt", nbins=10, title="Histograma MAPE Datos Corrida Retrianing")
fig.show()

## Histogrmas R2

In [9]:
fig = px.histogram(original, x="R2", nbins=8, title="Histograma R2 Datos Originales")
fig.show()

In [10]:
fig = px.histogram(original, x="R2_rt", nbins=8, title="Histograma R2 Datos Corrida 1")
fig.show()

In [11]:



fig = go.Figure()
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['MAPE'],
                    mode='lines+markers',
                    name='Datos Originales'))
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['MAPE_rt'],
                    mode='lines+markers',
                    name='Datos Corrida RT'))


fig.show()

In [12]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=2, cols=1)


fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['MAPE'],
                    mode='lines+markers',
                    name='Datos Originales'), 
                  row=1, col=1)
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['MAPE_rt'],
                    mode='lines+markers',
                    name='Datos Corrida RT'), 
                  row=2, col=1)
                                         
fig.update_layout(title_text="Graficos de MAPE", height=600)                                         
fig.show()

In [13]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['R2'],
                    mode='lines+markers',
                    name='Datos Originales'))
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['R2_rt'],
                    mode='lines+markers',
                    name='Datos Corrida 1'))

fig.show()

In [14]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=5, cols=1)


fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['R2'],
                    mode='lines+markers',
                    name='Datos Originales'), 
                  row=1, col=1)
fig.add_trace(go.Scatter(x=original['FECHA-HORA'], y=original['R2_rt'],
                    mode='lines+markers',
                    name='Datos Corrida 1'), 
                  row=2, col=1)
                                         
fig.update_layout(title_text="Graficos de R2", height=900)                                         
fig.show()